name: build_windows

on: [workflow_dispatch]

jobs:

  windows_msvc:
    runs-on: windows-2022
    env:
      VCPKG_DEFAULT_BINARY_CACHE: "${{github.workspace}}/vcpkg-cache"

    steps:
    - uses: actions/checkout@v4

    - name: Create cache directory
      run: mkdir ${{ env.VCPKG_DEFAULT_BINARY_CACHE }} -Force

    - uses: actions/cache@v4
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: ${{ hashFiles('vcpkg.json') }}-vcpkg-cache-x64-windows-static
        restore-keys: vcpkg-cache

    # Builds dependencies using vcpkg, leveraging cache
    - name: Run CMake
      run: cmake --preset=vcpkg-vs-github -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install" -DVCPKG_DEFAULT_TRIPLET=x64-windows-static -DVCPKG_TARGET_TRIPLET=x64-windows-static -DVCPKG_HOST_TRIPLET=x64-windows-static

    - name: Print CMake Cache
      run: cmake -LAH -B build

    # - name: Build
    #   run: cmake --build build --config Release

    - name: Install
      run: |
        cmake --build build --config Release --target install

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msvc-build
        path: build

    - name: Upload Install Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msvc-install
        path: install
