name: build_windows

on: [workflow_dispatch]

jobs:

  windows_msvc:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        library_type: [static, shared]

    env:
      VCPKG_DEFAULT_BINARY_CACHE: "${{github.workspace}}/vcpkg-cache"
      CMAKE_ARGS: ${{ matrix.library_type == 'static' && '-DBUILD_SHARED_LIBS=OFF -DVCPKG_DEFAULT_TRIPLET=x64-windows-static -DVCPKG_TARGET_TRIPLET=x64-windows-static -DVCPKG_HOST_TRIPLET=x64-windows-static' || '' }}
      TRIPLET: ${{ matrix.library_type == 'static' && 'x64-windows-static' || 'x64-windows' }}

    steps:
    - uses: actions/checkout@v4

    - name: Restore Vcpkg Cache
      uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: ${{ hashFiles('vcpkg.json') }}-vcpkg-cache-${{ env.TRIPLET }}

    # Builds dependencies using vcpkg, leveraging cache
    - name: Run CMake
      run: cmake --preset=vcpkg-vs-github -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install" ${{ env.CMAKE_ARGS }}

    # Always save cache in case later steps crashes
    - name: Save Vcpkg Cache
      uses: actions/cache/save@v4
      id: cache-save
      if: always() && steps.cache-restore.outputs.cache-hit != 'true'
      with:
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}

    - name: Print CMake Cache
      run: cmake -LAH -B build

    - name: Install
      run: |
        cmake --build build --config Release --target install

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msvc-build-${{ env.TRIPLET }}
        path: build

    - name: Upload Install Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msvc-install-${{ env.TRIPLET }}
        path: install
