name: build_windows

on: [workflow_dispatch]

env:
  CMAKE_FLAGS: -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS="-Werror"

jobs:

  windows_msvc:
    runs-on: windows-2022
    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}\vcpkg-cache

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ${{github.workspace}}\vcpkg-cache
        key: ${{ hashFiles('vcpkg.json') }}-vcpkg-cache
        restore-keys: vcpkg-cache

    - name: Create cache directory
      run: mkdir ${{env.VCPKG_DEFAULT_BINARY_CACHE}} -Force

    # Builds dependencies using vcpkg, leveraging cache
    # - name: Run CMake
    #   run: cmake --preset=vcpkg-vs-github

    # - name: Build
    #   run: cmake --build build --config Release

    - name: Install to directory so we can zip it up
      run: |
        cmake -B build -S . -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release ${{env.CMAKE_FLAGS}} -DCMAKE_TOOLCHAIN_FILE=$env{VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake
        cmake --build build --config Release --target install

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msvc-build
        path: build

    - name: Upload Install Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msvc-install
        path: install
